Initial wrapper of {Set,Get}OverlayTransformTrackedDeviceRelative
TheButlah/ovr_overlay pull request #10
Opened 2023-01-19 02:07 UTC by kitlith

I was working on wrappers anyway, so I decided I'd work on #7 while I was at it.

I'm proabably going to get a complaint that I should be wrapping sys::TrackedDeviceIndex_t in a newtype, I'll set that up somewhere eventually.

Obtaining the Matrix3x4, I'm following prior convention in this file, but it feels a bit non-idiomatic.

2023-01-22 02:04 UTC, TheButlah commented
will review later this week

2023-02-11 02:41 UTC, TheButlah commented on src/overlay.rs
> +    pub fn set_transform_overlay_tracked_device_relative(
the c++ functions are `setOverlayTransformTrackedDeviceRelative`. Did you intend on reversing the naming?

2023-02-11 20:28 UTC, kitlith commented on src/overlay.rs
> +    pub fn set_transform_overlay_tracked_device_relative(
I was following the naming convention of the functions below: `set_transform_overlay_relatve`/`get_transform_overlay_relative`

~~speaking of which, 'relatve' is a typo.~~

However, there is also precedent for dropping 'overlay' from the name: see `set_transform_absolute` calling `SetOverlayTransformAbsolute`.

In short, it's not currently consistent. I can take any of these three approaches, and fix the others to match if you want.

2023-02-11 21:47 UTC, TheButlah commented on src/overlay.rs
> +    pub fn set_transform_overlay_tracked_device_relative(
lets keep the name as close to the C++ code as possible. Feel free to correct any instances you find in the future to use that approach too

2023-02-12 22:57 UTC, TheButlah commented on src/overlay.rs
> +    /// Wrapper around SetOverlayTransformAbsolute.
```suggestion
    /// In c++: `SetOverlayTransformAbsolute`.
```

2023-02-12 22:57 UTC, TheButlah commented on src/overlay.rs
> +    /// Wrapper around GetOverlayTransformAbsolute.
```suggestion
    /// Wraps c++ `GetOverlayTransformAbsolute`.
```

2023-02-12 22:58 UTC, TheButlah commented on src/overlay.rs
> +    /// Wrapper around SetOverlayTransformTrackedDeviceRelative.
```suggestion
    /// Wraps c++ `SetOverlayTransformTrackedDeviceRelative`.
```

2023-02-12 22:58 UTC, TheButlah commented on src/overlay.rs
> +    /// Wrapper around GetOverlayTransformTrackedDeviceRelative.
```suggestion
    /// Wraps c++ `GetOverlayTransformTrackedDeviceRelative`.
```

2023-02-12 22:59 UTC, TheButlah commented on src/overlay.rs
> +    /// Wrapper around SetOverlayTransformOverlayRelative.
```suggestion
    /// Wraps c++ `SetOverlayTransformOverlayRelative`.
```

2023-02-12 23:00 UTC, TheButlah commented on src/overlay.rs
> +    /// Wrapper around GetOverlayTransformOverlayRelative.
```suggestion
    /// Wraps c++ `GetOverlayTransformOverlayRelative`.
```

2023-02-12 23:01 UTC, TheButlah approved these changes

2023-02-12 23:35 UTC, kitlith commented on src/overlay.rs
> +        TrackedDeviceIndex::new(index).or(EVROverlayError::new(sys::EVROverlayError::VROverlayError_RequestFailed).map(|_| unreachable!()))
This line is very yuck to me. In #11 I originally went with Option instead of Result because I didn't have a specific error type in mind. If we kept it as option, we could have the return type of this function be `Result<Option<TrackedDeviceIndex>, EVROverlayError>`, where a result of `Ok(None)` means "returned an invalid index successfully"

2023-02-12 23:50 UTC, TheButlah requested changes

2023-02-12 23:50 UTC, TheButlah commented on src/overlay.rs
> +    }
I don't understand the purpose of this code. Can't we just directly return the `EVROverlayError::new(err)`?

2023-02-13 00:00 UTC, kitlith commented on src/overlay.rs
> +    }
right, and you had me change the constructor of TrackedDeviceIndex to return a Result instead of returning an Option, which is what I was talking about in my own comment.

2023-02-13 00:14 UTC, merged