Add a wrapper around TrackedDeviceIndex_t.
TheButlah/ovr_overlay pull request #11
Opened 2023-01-22 05:12 UTC by kitlith

I'll rebase #8 and #10 on top of this one once this looks good.

2023-01-22 09:40 UTC, TheButlah requested changes

2023-01-22 09:40 UTC, TheButlah commented on src/lib.rs
> +    pub const fn new(index: sys::TrackedDeviceIndex_t) -> Option<Self> {
I would opt for a result here instead.

2023-01-22 09:40 UTC, TheButlah commented on src/lib.rs
> +        // something something custom niche? meh.
```suggestion
```

2023-01-22 09:40 UTC, TheButlah commented on src/lib.rs
> +    pub const fn hmd() -> Self {
use associated constant instead of const fns for this type of thing

2023-01-22 09:40 UTC, TheButlah commented on src/lib.rs
> +    pub const fn is_other(&self) -> bool {
bwuh

I would keep this whole function commented out, with a request imploring the reader to open an issue on our repository if they end up needing it.

2023-01-22 09:40 UTC, TheButlah commented on sys/src/lib.rs
> +    generate!("vr::k_unTrackedDeviceIndex_Hmd")
are these able to be POD?

2023-01-22 19:36 UTC, kitlith commented on sys/src/lib.rs
> +    generate!("vr::k_unTrackedDeviceIndex_Hmd")
generate_pod!() generates an error on these constants, though maybe it wouldn't if I threw a generate_pod!() on TrackedDeviceIndex_t first? I'm not sure it makes much of a difference though, it should result in the same constant being available to rust either way.

2023-01-22 19:38 UTC, kitlith commented on sys/src/lib.rs
> +    generate!("vr::k_unTrackedDeviceIndex_Hmd")
> Unable to make vr::k_unTrackedDeviceIndexInvalid POD because we never saw a struct definition

is the exact error... which makes sense because there is no struct, it's just a typedef.

2023-01-22 19:50 UTC, kitlith commented on sys/src/lib.rs
> +    generate!("vr::k_unTrackedDeviceIndex_Hmd")
I've added an explicit `generate_pod!("vr::TrackedDeviceIndex_t")` above the constants for the sake of being explicit, but I can't change the constants from generate to generate_pod.

2023-01-22 19:54 UTC, kitlith commented on src/lib.rs
> +    pub const fn new(index: sys::TrackedDeviceIndex_t) -> Option<Self> {
Not resolving yet, as I've only changed it to `Result<Self, ()>` since I don't have a good error type for this yet.

Answer might be to make a unit struct that has conversions into relevant error types eventually.

2023-02-11 02:38 UTC, TheButlah commented on src/lib.rs
> +            // Is this ever going to come up from an otherwise successful result?
```suggestion
            // TODO: Is this ever going to come up from an otherwise successful result?
```

2023-02-11 02:38 UTC, TheButlah approved these changes

2023-02-12 07:30 UTC, merged