Initial bindings for input subsystem.
TheButlah/ovr_overlay pull request #6
Opened 2022-07-05 00:53 UTC by kitlith

Includes most things that the feeder app/overlay wants, aside from GetOriginLocalizedName (which needs a bitset I haven't implemented yet).

Currently using types directly from sys, might want to wrap some of these types.

PR is currently a draft, because at the very least there is one more function I intend to implement, then I'll work on wrappers for types from sys.

2022-08-22 04:56 UTC, kitlith commented
Marking as ready for review. I'm not going to bother to implement `GetOriginLocalizedName` at the current time, since we're not working on porting the feeder over to rust quite yet.

This means the main obstacle for this PR at the moment is the direct usage of sys::* types.

2022-08-22 07:22 UTC, TheButlah commented
I might not have time to review this as I'm about to go on vacation. How high priority is it for me to review?

2022-08-22 10:04 UTC, kitlith commented
Not very high, since there's still some sys:: types being used that I know that you'll want fixed. The point of marking it as reading for review is to say "hey, this isn't blocked on me coming back and implementing a method i said i was going to implement before".

Enjoy your vacation, don't worry about it.

2022-08-23 05:07 UTC, TheButlah requested changes
Thanks so much for the contribution! I had several comments on this PR, although many of them were just requesting some clarification and the rest were minor nits.

Biggest thing is that I want to make the input subsystem a non-default feature, since I think this will more clearly segment up the OpenVR api and communicate that we do not support everything yet, and may never decide to support everything.

2022-08-23 05:07 UTC, TheButlah commented on src/input.rs
> +        seconds_from_now: f32,
We can have a `trait ToSeconds` that is implemented both for std::time::Duration and for f32. This lets the user use either the more efficient f32 or the more rust `std::time::Duration`.

If you would like, I can implement this in a followup PR, if you wish to punt this to focus on this current PR getting merged sooner. In that case, just add a TODO comment about the trait.

2022-08-23 05:17 UTC, kitlith commented on src/lib.rs
> +    pub fn input_mngr(&self) -> input::InputManager<'_> {
I did it that way purely because it was the only use of InputManager in the file. I don't mind changing it.

2022-08-23 05:18 UTC, TheButlah commented on src/lib.rs
> +    pub fn input_mngr(&self) -> input::InputManager<'_> {
yes please, just for consistency

2022-08-23 05:23 UTC, kitlith commented on src/input.rs
> +                .map(|_| unreachable!());
`EVRInputError::new()` returns `Result<(), EVRInputError>`, but the function returns `Result<ActionSetHandle, EVRInputError>`, so I either had to use map just to get the types to match up.

I could change it to use `?`, and unreachable afterwards to avoid rust complaining that I'm not returning a value in that branch of the if/else expression.

2022-08-23 05:28 UTC, kitlith commented on src/input.rs
> +                std::mem::size_of::<sys::VRActiveActionSet_t>() as u32,
From what I understand from openvr's API, this is a case where they've defined a struct VRActiveActionSet_t that they want to leave open to future expansion. So you also pass the sizeof the struct that you're aware of, so that they only write data in the area that the application is aware of (if the openvr api version at runtime is newer than the openvr api version that was compiled against).

2022-08-23 05:34 UTC, kitlith commented on src/lib.rs
> +    pub fn input_mngr(&self) -> input::InputManager<'_> {
Aside, this does reduce the number of places that feature-gating needs to occur, since i can just gate this function and the module without needing to also gate a use.

2022-08-23 05:57 UTC, kitlith commented on src/input.rs
> +        let path = if let Ok(s) = CString::new(path.to_string_lossy().as_bytes()) {
`Cow<str>` does not implement `Into<Vec<u8>>`, which is what the CString constructor wants. this leaves `as_ref`, `as_bytes`, or `into_owned`, the latter of which explicitly performs a copy if `to_string_lossy` didn't perform a copy.

2022-08-23 06:03 UTC, kitlith commented on src/input.rs
> +pub struct ActionSetHandle(sys::VRActionSetHandle_t);
not sure. we should probably make an effort to be compatible with things that are using the sys crate directly, so that they can move handles in and out without too much difficulty, but we could say that's what the from and into impls are for?

2023-01-08 00:41 UTC, kitlith commented on src/input.rs
> +        seconds_from_now: f32,
Duration apparently has a const fn for this, so maybe we should just use Duration. implementing trait for now.

2023-01-08 00:47 UTC, kitlith commented on src/input.rs
> +pub struct ActionSetHandle(sys::VRActionSetHandle_t);
I'm inclined to punt on this for now.

2023-01-08 02:31 UTC, kitlith commented on src/input.rs
> +        sets: &mut [sys::VRActiveActionSet_t],
so, apparently autocxx doesn't derive anything on structs by default. updating autocxx to a newer version only removes some derives on types that previously had them.

aside, I don't think there's any reason we couldn't add trait impls inside of the sys crate itself?

2023-01-18 01:06 UTC, TheButlah approved these changes

2023-01-18 01:28 UTC, TheButlah approved these changes

2023-01-18 01:31 UTC, merged