Implement getting TrackedDeviceProperties.
TheButlah/ovr_overlay pull request #8
Opened 2023-01-18 04:14 UTC by kitlith

I wish that we weren't essentially duplicating the FFI enum here. I put the regexes I used to generate the type-safe enums in a comment, at least.

do you want this feature gated?

any other concerns?

2023-01-18 04:29 UTC, TheButlah commented
All new subsystems should be feature gated, yeah

2023-01-19 01:45 UTC, kitlith commented
This is still technically missing the following properties:
 - Prop_ParentContainer (no type mentioned, but is supposed to be opaque to us anyway)
 - Prop_CameraToHeadTransforms_Matrix34_Array
 - Prop_CameraWhiteBalance_Vector4_Array
 - Prop_CameraDistortionFunction_Int32_Array
 - Prop_CameraDistortionCoefficients_Float_Array
 - Prop_DisplayAvailableFrameRates_Float_Array
but I don't really feel like dealing with arrays right now. these are fairly niche, anyway.

2023-01-19 01:54 UTC, kitlith commented
should maybe make wrapper around `sys::TrackedDeviceIndex_t`, but it should be outside the system module as overlay module will also want it.

2023-01-22 02:04 UTC, TheButlah commented
will review later this week

2023-02-12 08:55 UTC, kitlith commented
I forgot to make the props module pub >_> will do that when i get the chance.

2023-02-12 23:41 UTC, kitlith commented
Open question: how do we want to deal with the non-camel case property names in enums? currently we generate warnings.

We could:
 - Munge the names further
 - Silence the warnings, and leave them as-is.

2023-02-13 00:18 UTC, TheButlah commented
sys types can

> Open question: how do we want to deal with the non-camel case property names in enums? currently we generate warnings.
> 
> We could:
> 
>     * Munge the names further
> 
>     * Silence the warnings, and leave them as-is.

Its ok to `#[allow()]` these enums, since they have a specific meaning in OpenVR and they are autogenerated from a regex

2023-02-13 00:26 UTC, kitlith commented
ah i didn't check the test. *sigh*

Will allow the enum and fix the test thing.

2023-02-13 00:46 UTC, kitlith commented
Had a thought while I was working on this: ideally we'd be referencing the enum values from the enum in the sys crate instead of embedding them directly here, right? But this might be something to punt on for now.

2023-02-13 09:24 UTC, TheButlah commented
> But this might be something to punt on for now.

Well, that might remove a ton of (possibly brittle) code.

Yes if the sys crate exposes it as an enum then we should directly reference that. IDK why the sys crate is using enums thoguh - C++ enums can be any integer it doesn't have to be one of the specified variants. So for safety, things like CXX and bindgen don't use enums in rust to represent c/c++ enums.

Is autocxx being a bit evil here?

2023-02-13 16:24 UTC, kitlith commented
i might be blanking and they're constants instead of an enum.

It won't change the amount of code either way, just makes it less brittle.

2023-02-13 19:48 UTC, kitlith commented
Per discord discussion, will be splitting into MVP (just the bits that deal with the sys enum) and another PR for the new enums that are clear on types.

2023-02-21 20:32 UTC, TheButlah requested changes

2023-02-21 20:32 UTC, TheButlah commented on src/system.rs
> +                .unwrap_or_else(|s| s.into_cstring().to_string_lossy().into_owned())
I don't like the idea of always lossily converting to a utf-8 string. It should be up to the user to handle that.

I suggest we do all of the following:
- Add an impl on `&CStr`. Have a static buffer of bytes that is the [maximum size](https://github.com/ValveSoftware/openvr/blob/1a0ea26642e517824b66871e6a12280a426cfec3/headers/openvr.h#L574) of an OpenVR String. This is the buffer you pass to openvr, and you can skip the first function call where you check for the size, as it is guaranteed to be smaller. OpenVR will copy into that buffer, tell you the size, and you can call [`CStr::from_bytes_with_nul`](https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.from_bytes_with_nul) to get the CStr (and panic if it is an error).
- Keep the impl on `CString` - it seems fine.
- Don't bother implementing anything for `String` or `&str`, the caller can use the appropriate functions on `CStr` and `CString` for that.

2023-02-22 03:42 UTC, kitlith commented on src/system.rs
> +}
I can rename it to mod private.

It's called SealedPropertyType because, eventually, post-MVP, there might be a separate sealed trait. Maybe that's overkill, though, and since it's not part of the public interface, we can rename it just fine.

2023-02-22 03:51 UTC, kitlith commented on src/system.rs
> +// thought: other matrix types?
My thought process here: TODO means we actively want to support other matrix types here (i.e. nalgebra, mint). I don't know that we want to do that (we might just want to go through conversions of Matrix3x4 anyway) so it's a thought, not a TODO.

Unless you actively want to support other matrix types here, in which case, by all means.

2023-02-22 03:55 UTC, kitlith commented on src/system.rs
> +pub trait PropertyType: SealedPropertyType + Sized {
No. That's stealing the name of the trait used for the non-MVP version of the API where you don't have to worry about pairing a property and a type manually, and having that checked at runtime.

This trait is implemented on possible return types, not on *properties*.

2023-02-22 03:59 UTC, kitlith commented on src/system.rs
> +    pub fn get_property_sys<T: PropertyType>(
I'm okay with this rename as long as we add a _sys postfix or some other delination, to make room for the non-mvp version of the API that doesn't require the user to manually pair the property and the return type.

Alternatively, I can see if I can try fitting them into the same function, but that's likely going to require re-introducing some of the machinery that I was hoping to avoid to keep the MVP simple.

2023-02-22 04:12 UTC, kitlith commented on src/system.rs
> +                .unwrap_or_else(|s| s.into_cstring().to_string_lossy().into_owned())
I'm likely to defer the &CStr impl, because I'm not sure I can make it properly correct and safe. It has an inherent idea of "this is valid only until the next time I call this function" and I'm not quite sure how to encode that properly.

The idea behind the String impl is to be a convienent default, and if the user want to handle it themselves, they can use the CString impl, specifically avoiding "always lossily converting to utf-8" if they want. I can still remove it if you think that's a bad default, but it seems like a very useful and common default if you want to display it to the user.

2023-02-22 17:38 UTC, TheButlah commented on src/system.rs
> +}
There indeed could be different sealed traits in each module - but since it's private it is ok. Ultimately what matters is that users understand it is implementation detail. So I still prefer `private::Sealed` as a convention, even if there are multiple of those in different modules

2023-02-22 17:40 UTC, TheButlah commented on src/system.rs
> +// thought: other matrix types?
Ok, then `TODO: Decide if we want to support more types like matrices`

2023-02-22 17:48 UTC, TheButlah commented on src/system.rs
> +                .unwrap_or_else(|s| s.into_cstring().to_string_lossy().into_owned())
It is easy and safe to implement. We borrow the system as &mut in these functions so it is not going to be called concurrently. And the lifetime of the returned CStr should be the lifetime of the mut ref to the system, rather than static (even though the underlying buffer is static). The borrow checker will ensure that this is safe.
You can even store the buffer as a boxed slice in the system manager instead of a static variable, to improve the safety if you want.

If you are unsure how to proceed, defer the CStr to a separate PR. But I still don't think it's a good idea to provide a String implementation. I wish to lean towards "less user features" rather than more rn, in this projects maintenance

2023-02-22 17:51 UTC, TheButlah commented on src/system.rs
> +    pub fn get_property_sys<T: PropertyType>(
I guess I don't understand what the non-mvp is here. Can you give a brief summary?

2023-02-22 18:34 UTC, kitlith commented on src/system.rs
> +    pub fn get_property_sys<T: PropertyType>(
non MVP is: user passes a property. We already know what type of property it is, therefore we already know the return type, it can be implicit. that's where all the enum duplication was coming from before, to tie a property to its return type.

2023-02-23 06:44 UTC, kitlith commented on src/system.rs
> +                .unwrap_or_else(|s| s.into_cstring().to_string_lossy().into_owned())
> You can even store the buffer as a boxed slice in the system manager instead of a static variable, to improve the safety if you want.

That is, in fact, exactly the only way to make it safe, because otherwise there's nothing stopping you from creating two instances of the system manager at once and stomping all over the static storage by using different system managers.

2023-02-23 08:52 UTC, kitlith commented on src/system.rs
> +                .unwrap_or_else(|s| s.into_cstring().to_string_lossy().into_owned())
current attempt at implementing runs into this:
```
error[E0308]: method not compatible with trait
   --> src\system.rs:113:5
    |
113 | /     fn get(
114 | |         index: TrackedDeviceIndex,
115 | |         system: &'a mut SystemManager,
116 | |         prop: sys::ETrackedDeviceProperty,
117 | |     ) -> PropResult<&'a CStr> {
    | |_____________________________^ lifetime mismatch
    |
    = note: expected fn pointer `fn(TrackedDeviceIndex, &mut system::SystemManager<'_>, ETrackedDeviceProperty) -> std::result::Result<_, _>`
               found fn pointer `fn(TrackedDeviceIndex, &'a mut system::SystemManager<'_>, ETrackedDeviceProperty) -> std::result::Result<_, _>`
note: the anonymous lifetime as defined here...
   --> src\system.rs:115:25
    |
115 |         system: &'a mut SystemManager,
    |                         ^^^^^^^^^^^^^
note: ...does not necessarily outlive the lifetime `'a` as defined here
   --> src\system.rs:112:6
    |
112 | impl<'a> TrackedDevicePropertyValue for &'a CStr {
    |      ^^

```

2023-02-23 17:15 UTC, TheButlah commented on src/system.rs
> +                .unwrap_or_else(|s| s.into_cstring().to_string_lossy().into_owned())
> That is, in fact, exactly the only way to make it safe, because otherwise there's nothing stopping you from creating two instances of the system manager at once and stomping all over the static storage by using different system managers.

<img width="702" alt="Screenshot 2023-02-23 at 12 12 31 PM" src="https://user-images.githubusercontent.com/6969415/220980465-97109374-0109-4342-8883-8b99df43919d.png">

The entire library is a singleton because of the above pattern enforced both by us and OpenVR. So using static storage like that should be fine.
HOWEVER, when I first read your statement I went "GUH" because *I didn't remember that* so the fact that it was a singleton was merely me getting lucky. I think thats a good reminder for me not to be clever, and do things safely (i.e. store the buffer in the system itself).

2023-02-23 18:29 UTC, kitlith commented on src/system.rs
> +                .unwrap_or_else(|s| s.into_cstring().to_string_lossy().into_owned())
If we want to setup a more thorough singleton pattern, we'd have to follow something similar to how embedded peripherals work. But that doesn't really match the semantics of openvr at all, so.

2023-02-23 19:48 UTC, TheButlah commented on src/system.rs
> +                .unwrap_or_else(|s| s.into_cstring().to_string_lossy().into_owned())
This led to this discover: #16

2023-02-23 19:58 UTC, TheButlah commented on src/system.rs
> +pub trait TrackedDevicePropertyValue: private::Sealed + Sized {
```suggestion
pub trait TrackedDeviceProperty: private::Sealed + Sized {
```
The name of this trait is still confusing. You are returning this when you call `get_tracked_device_property`. So it *is* a `TrackedDeviceProperty`. If you have a different intent you wish to add later after this MVP, such as a way to differentiate between the rust-native types and the types that are actually stored in openvr, we can add that in a later PR. For now, I will apply some suggestions to this and merge.

2023-02-23 19:58 UTC, TheButlah commented on src/system.rs
> +        impl TrackedDevicePropertyValue for $ty {
```suggestion
        impl TrackedDeviceProperty for $ty {
```

2023-02-23 19:58 UTC, TheButlah commented on src/system.rs
> +impl TrackedDevicePropertyValue for CString {
```suggestion
impl TrackedDeviceProperty for CString {
```

2023-02-23 19:58 UTC, TheButlah commented on src/system.rs
> +    pub fn get_tracked_device_property<T: TrackedDevicePropertyValue>(
```suggestion
    pub fn get_tracked_device_property<T: TrackedDeviceProperty>(
```

2023-02-23 19:58 UTC, TheButlah commented on src/system.rs
> +// impl<'a> TrackedDevicePropertyValue for &'a CStr {
```suggestion
// impl<'a> TrackedDeviceProperty for &'a CStr {
```

2023-02-23 20:40 UTC, kitlith commented on src/system.rs
> +pub trait TrackedDevicePropertyValue: private::Sealed + Sized {
I'm thinking about this as a key value map. The property is the key, the value of that property is the value. I guess you're thinking of it as the name of the property being the key, and the property itself being a value?

2023-02-23 20:41 UTC, kitlith commented on src/system.rs
> +pub trait TrackedDevicePropertyValue: private::Sealed + Sized {
To expand: I do not consider a Matrix3x4 or a u64 to be a property. A CurrentTrackingUniverse is a property.

2023-02-23 20:43 UTC, TheButlah commented on src/system.rs
> +pub trait TrackedDevicePropertyValue: private::Sealed + Sized {
yes, precisely. I know you may revise this in a later PR though, and I'm 100% open to that (with appropriate discussion, of course)

2023-02-23 20:47 UTC, kitlith commented on src/system.rs
> +pub trait TrackedDevicePropertyValue: private::Sealed + Sized {
If you want to separate it into PropertyNames being the key and Properties being the value, fine, but we need nanes for both concepts, and I'd prefer them to make sense.

2023-02-23 20:49 UTC, TheButlah commented on src/system.rs
> +pub trait TrackedDevicePropertyValue: private::Sealed + Sized {
Lets please punt this to a later PR.

2023-02-23 21:00 UTC, kitlith commented on src/system.rs
> +pub trait TrackedDevicePropertyValue: private::Sealed + Sized {
Fine. Go ahead and merge it then.

2023-02-23 21:06 UTC, TheButlah commented
To help with the merge conflicts, I'm almost done with #17 rn

2023-02-23 21:44 UTC, TheButlah commented on src/system.rs
> +    string_buf: Vec<u8>,
```suggestion
```

2023-02-23 21:44 UTC, TheButlah approved these changes

2023-02-23 21:46 UTC, TheButlah reviewed
guh

2023-02-23 21:51 UTC, kitlith commented
hold on a second, I found a solution to the &CStr bit. lifetimes are a bit messy though.

2023-02-23 21:51 UTC, TheButlah commented
> hold on a second, I found a solution to the &CStr bit. lifetimes are a bit messy though.

later pr, not this one. About to merge.

2023-02-23 21:52 UTC, kitlith commented
oh. sorry.

2023-02-23 21:54 UTC, kitlith commented
there, extra commit removed, will punt to PR.

2023-02-23 21:58 UTC, kitlith commented
ah, yes, CStr is unused, because the relevant impl is commented out.

2023-02-23 22:04 UTC, merged

2023-02-23 22:05 UTC, TheButlah commented
bless, its done 😅